import "./globals.css";

import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";

const noto = Noto_Sans_JP({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-not-sans-jp",
});

export const metadata: Metadata = {
  title: "Todo App with Next.js,Typescript",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="w-full h-full">
      <body className={`w-full h-full ${noto.className} bg-nord0 text-nord4`}>{children}</body>
    </html>
  );
}
